// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq0eh9bpPSyNstrypwkn7Gzw-edJFchP8',
    appId: '1:617719664520:web:59693870288e52b318b43d',
    messagingSenderId: '617719664520',
    projectId: 'dacs3-444a9',
    authDomain: 'dacs3-444a9.firebaseapp.com',
    storageBucket: 'dacs3-444a9.firebasestorage.app',
    measurementId: 'G-KMJFN8ZERJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjGCqDaqyNBne-j7tkJQ8XuMHCBXPQDpc',
    appId: '1:617719664520:android:a6f3bbdf5a8f088d18b43d',
    messagingSenderId: '617719664520',
    projectId: 'dacs3-444a9',
    storageBucket: 'dacs3-444a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCewVceRga-PBxt7k1gwaRTrx9GuOWwkbY',
    appId: '1:617719664520:ios:6d3b4a6da8cf05f418b43d',
    messagingSenderId: '617719664520',
    projectId: 'dacs3-444a9',
    storageBucket: 'dacs3-444a9.firebasestorage.app',
    iosBundleId: 'com.example.smartDormVkuDacs3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCewVceRga-PBxt7k1gwaRTrx9GuOWwkbY',
    appId: '1:617719664520:ios:6d3b4a6da8cf05f418b43d',
    messagingSenderId: '617719664520',
    projectId: 'dacs3-444a9',
    storageBucket: 'dacs3-444a9.firebasestorage.app',
    iosBundleId: 'com.example.smartDormVkuDacs3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq0eh9bpPSyNstrypwkn7Gzw-edJFchP8',
    appId: '1:617719664520:web:b913bfdd8001a4e718b43d',
    messagingSenderId: '617719664520',
    projectId: 'dacs3-444a9',
    authDomain: 'dacs3-444a9.firebaseapp.com',
    storageBucket: 'dacs3-444a9.firebasestorage.app',
    measurementId: 'G-VKDXQJPQ2M',
  );
}